OtaghMazandaran/Controllers/PlaceController.cs
using DataLayer.Context;
using DataLayer.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace OtaghMazandaran.Controllers
{
    public class PlaceController : Controller
    {
        private IPlaceRepository _db;
        public PlaceController(IPlaceRepository placeRepository)
        {
            _db = placeRepository;
        }
        public IActionResult Index()
        {
            return View(_db.GetAll());
        }
        public IActionResult Create() { return View(); }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind(include: "PlaceName,PlaceDescription")] DataLayer.Models.Place src)
        {
            if(ModelState.IsValid == false)
            {
                return View(src);
            }
            _db.Insert(src);
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id) { return View(_db.Get(id)); }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind(include: "PlaceId,PlaceName,PlaceDescription")] DataLayer.Models.Place src)
        {
            if (ModelState.IsValid == false)
            {
                return View(src);
            }
            _db.Update(src);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id) 
        {
            ViewBag.CanDelete = _db.CanDelete(id);
            return View(_db.Get(id)); 
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePlace(int PlaceId)
        {
            _db.Delete(PlaceId);
            return RedirectToAction("Index");
        }
    }
}

OtaghMazandaran/Controllers/PropertyController.cs
using DataLayer.DTOs;
using DataLayer.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace OtaghMazandaran.Controllers
{
    public class PropertyController : Controller
    {
        private IPropertyRepository _db;
        private IPlaceRepository _place;
        public PropertyController(IPropertyRepository propertyRepository,IPlaceRepository placeRepository)
        {
            _db = propertyRepository;
            _place = placeRepository;
        }
        public IActionResult Index(int id = 0,string PropertyName = "" ,string NewPropertyNumber = "")
        {
            var rslt = _db.GetAll();
            if(id != 0) rslt = _db.GetAll(id);

            if(string.IsNullOrEmpty(PropertyName) == false)
            {
                rslt = rslt.Where(u=>u.PropertyName.Contains(PropertyName));
            }
            if (string.IsNullOrEmpty(NewPropertyNumber) == false)
            {
                rslt = rslt.Where(u => u.NewPropertyNumber.Contains(NewPropertyNumber));
            }
            ViewBag.Place = id;
            ViewBag.PropertyName = PropertyName;
            ViewBag.NewPropertyNumber = NewPropertyNumber;
            return View(rslt);
        }
        public IActionResult PrintList(int id = 0, string PropertyName = "", string NewPropertyNumber = "")
        {
            var rslt = _db.GetAll();
            if (id != 0) rslt = _db.GetAll(id);

            if (string.IsNullOrEmpty(PropertyName) == false)
            {
                rslt = rslt.Where(u => u.PropertyName.Contains(PropertyName));
            }
            if (string.IsNullOrEmpty(NewPropertyNumber) == false)
            {
                rslt = rslt.Where(u => u.NewPropertyNumber.Contains(NewPropertyNumber));
            }
            return View(rslt);
        }
        public IActionResult Create()
        {
            ViewBag.Places = _place.GetAll().Select(u => new SelectListItem
            {
                Value = u.PlaceId.ToString(),
                Text = u.PlaceName
            }).ToList() as List<SelectListItem>;

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind(include: "PropertyName,OldPropertyNumber,NewPropertyNumber,PropertyDescription,PlaceId")]CreatePropertyMV src)
        {
            src.CreatedByUser = Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier));
            if(ModelState.IsValid == false)
            {
                ViewBag.Places = _place.GetAll().Select(u => new SelectListItem
                {
                    Value = u.PlaceId.ToString(),
                    Text = u.PlaceName
                }).ToList() as List<SelectListItem>;

                return View(src);
            }
            _db.Insert(src);
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            ViewBag.Places = _place.GetAll().Select(u => new SelectListItem
            {
                Value = u.PlaceId.ToString(),
                Text = u.PlaceName
            }).ToList() as List<SelectListItem>;

            return View(_db.GetforUpdateMV(id));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind(include: "PropertyId,PropertyName,OldPropertyNumber,NewPropertyNumber,PropertyDescription,PlaceId")]UpdatePropertyMV src)
        {
            src.UpdatedByUser = Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier));
            if (ModelState.IsValid == false)
            {
                ViewBag.Places = _place.GetAll().Select(u => new SelectListItem
                {
                    Value = u.PlaceId.ToString(),
                    Text = u.PlaceName
                }).ToList() as List<SelectListItem>;

                return View(src);
            }
            _db.Update(src);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id) { return View(_db.Get(id)); }
        [HttpPost][ValidateAntiForgeryToken]
        public IActionResult DeleteProperty(int PropertyId)
        {
            _db.Delete(PropertyId, Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier)));
            return RedirectToAction("Index");
        }
    }
}

OtaghMazandaran/Controllers/UserController.cs
using DataLayer.Models;
using DataLayer.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace OtaghMazandaran.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        IUserRepository _db;
        public UserController(IUserRepository userRepository)
        {
            _db = userRepository;
        }
        public IActionResult Index() { return View(_db.GetAll()); }
        #region Edit My Profile
        public IActionResult EditMe()
        {
            int userid = Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier));
            DataLayer.Models.AdminUser usr = _db.Get(userid);
            return View(usr);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditMe([Bind(include: "FullName,Phone,UserName,Password,IsActive")] AdminUser Src)
        {
            ModelState.Remove("Password");
            if (!ModelState.IsValid)
            {
                return View(Src);
            }

            int userid = Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier));
            DataLayer.Models.AdminUser usr = _db.Get(userid);

            if (usr.Phone != Src.Phone)
            {
                int phonexisted = _db.IsPhoneExisted(Src.Phone);
                if (phonexisted != 0 && phonexisted != usr.AdminUserId)
                {
                    ModelState.AddModelError("Phone", "این شماره همراه برای کاربر دیگری ثبت شده");
                }
                else usr.Phone = Src.Phone;
            }

            if (usr.UserName != Src.UserName)
            {
                int usrnamexisted = _db.IsUserNameExisted(Src.UserName);
                if (usrnamexisted != 0 && usrnamexisted != usr.AdminUserId)
                {
                    ModelState.AddModelError("UserName", "این نام کاربری برای کاربر دیگری ثبت شده");
                }
                else usr.UserName = Src.UserName;
            }

            if (string.IsNullOrEmpty(Src.Password) == false)
            {
                usr.Password = Src.Password;
            }

            usr.FullName = Src.FullName;
            usr.IsActive = Src.IsActive;

            _db.Update(usr);
            return View(usr);
        }

        [HttpPost]
        public IActionResult DeleteMyPhoto()
        {
            int userid = Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier));
            DataLayer.Models.AdminUser usr = _db.Get(userid);

            if (usr.UserImage != "Default.png")
            {
                System.IO.File.Delete(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", "admin", usr.UserImage));
            }
            usr.UserImage = "Default.png";
            _db.Update(usr);
            return RedirectToAction("EditMe");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ChangeMyPhoto(IFormFile ImgUp)
        {
            int userid = Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier));
            DataLayer.Models.AdminUser usr = _db.Get(userid);

            if (usr.UserImage != "Default.png")
            {
                System.IO.File.Delete(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", "admin", usr.UserImage));
            }
            usr.UserImage = string.Concat(Guid.NewGuid(), Path.GetExtension(ImgUp.FileName));
            string filepath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", "admin", usr.UserImage);
            using (var stream = new FileStream(filepath, FileMode.Create))
            {
                ImgUp.CopyTo(stream);
            }
            _db.Update(usr);
            return RedirectToAction("EditMe");
        }
        #endregion
        public IActionResult ActiveUser(int id)
        {
            _db.ActiveUser(id);
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id) { return View(_db.Get(id)); }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind(include: "AdminUserId,FullName,UserName,Password,Phone,IsActive")] AdminUser src)
        {
            ModelState.Remove("Password");
            if (!ModelState.IsValid)
            {
                return View(src);
            }
            AdminUser rslt = _db.Get(src.AdminUserId);
            rslt.FullName = src.FullName;
            if (rslt.UserName != src.UserName)
            {
                int usrnamexisted = _db.IsUserNameExisted(src.UserName);
                if (usrnamexisted != 0 && usrnamexisted != rslt.AdminUserId)
                {
                    ModelState.AddModelError("UserName", "این نام کاربری برای کاربر دیگری ثبت شده");
                }
                else rslt.UserName = src.UserName;
            }
            if (string.IsNullOrEmpty(src.Password) == false)
            {
                rslt.Password = src.Password;
            }
            if (rslt.Phone != src.Phone)
            {
                int phonexisted = _db.IsPhoneExisted(src.Phone);
                if (phonexisted != 0 && phonexisted != rslt.AdminUserId)
                {
                    ModelState.AddModelError("Phone", "این شماره همراه برای کاربر دیگری ثبت شده");
                }
                else rslt.Phone = src.Phone;
            }
            rslt.IsActive = src.IsActive;
            _db.Update(rslt);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id) 
        {
            ViewBag.CanDelete = _db.CanDelete(id);
            return View(_db.Get(id)); 
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteUser(int AdminUserId)
        {
            _db.Delete(AdminUserId);
            return RedirectToAction("Index");
        }
    }
}

OtaghMazandaran/Views/Shared/_AuthLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="fa" class="light-style customizer-hide" dir="rtl" data-theme="theme-default" data-assets-path="/" data-template="vertical-menu-template-no-customizer">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="robots" content="noindex" />
    <meta name="robots" content="nofollow" />
    <title>لایت کمپانی | @ViewData["Title"]</title>

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="~/favicon.ico">
    <!-- Icons -->
    <link rel="stylesheet" href="~/fonts/boxicons.css">
    <link rel="stylesheet" href="~/fonts/fontawesome.css">
    <!-- Core CSS -->
    <link rel="stylesheet" href="~/css/core-dark.css">
    <link rel="stylesheet" href="~/css/theme-default-dark.css">
    <link rel="stylesheet" href="~/css/demo.css">
    <link rel="stylesheet" href="~/css/rtl.css">

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="~/libs/perfect-scrollbar/perfect-scrollbar.css">
    <link rel="stylesheet" href="~/libs/typeahead-js/typeahead.css">
    <!-- Vendor -->
    <link rel="stylesheet" href="~/libs/formvalidation/dist/css/formValidation.min.css">

    <!-- Page CSS -->
    <!-- Page -->
    <link rel="stylesheet" href="~/css/pages/page-auth.css">
    <!-- Helpers -->
    <script src="~/js/helpers.js"></script>
    <script src="~/js/config.js"></script>
</head>

<body>
    <!-- Content -->

    <div class="container-xxl">
        <div class="authentication-wrapper authentication-basic container-p-y">
            <div class="authentication-inner py-4">
                @RenderBody()
            </div>
        </div>
    </div>

    <!-- / Content -->
    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="~/lib/jquery/dist/jquery.slim.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/libs/hammer/hammer.js"></script>
    <script src="~/libs/i18n/i18n.js"></script>
    <script src="~/libs/typeahead-js/typeahead.js"></script>
    <script src="~/js/menu.js"></script>
    <!-- endbuild -->
    <!-- Vendors JS -->
    <script src="~/libs/formvalidation/dist/js/FormValidation.min.js"></script>
    <script src="~/libs/formvalidation/dist/js/plugins/Bootstrap5.min.js"></script>
    <script src="~/libs/formvalidation/dist/js/plugins/AutoFocus.min.js"></script>

    <!-- Main JS -->
    <script src="~/js/main.js"></script>

    <!-- Page JS -->
    <script src="~/js/pages-auth.js"></script>
    @RenderSection("Scripts",required:false)
</body>
</html>

OtaghMazandaran/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa" class="dark-style layout-navbar-fixed layout-menu-fixed" dir="rtl" data-theme="theme-default" data-assets-path="/" data-template="vertical-menu-template-no-customizer-starter">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="robots" content="noindex" />
    <meta name="robots" content="nofollow" />
    <title>لایت کمپانی | @ViewData["Title"]</title>
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="~/favicon.ico">
    <!-- Icons -->
    <link rel="stylesheet" href="~/fonts/boxicons.css">
    <link rel="stylesheet" href="~/fonts/fontawesome.css">
    <!-- Core CSS -->
    <link rel="stylesheet" href="~/css/core-dark.css">
    <link rel="stylesheet" href="~/css/theme-default-dark.css">
    <link rel="stylesheet" href="~/css/demo.css">
    <link rel="stylesheet" href="~/css/rtl.css">

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="~/lib/perfect-scrollbar/perfect-scrollbar.css">
    <link rel="stylesheet" href="~/lib/typeahead-js/typeahead.css">
    <!-- Vendor -->
    <link rel="stylesheet" href="~/lib/formvalidation/dist/css/formValidation.min.css">

    <!-- Page CSS -->
    @RenderSection("Style", required: false)
    <!-- Helpers -->
    <script src="~/js/helpers.js"></script>
    <script src="~/js/config.js"></script>
</head>

<body>
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">
            <!-- Menu -->

            <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
                <div class="app-brand demo">
                    <a asp-controller="Home" asp-action="Index" class="app-brand-link">
                        <span class="app-brand-logo demo">
                            <img src="~/favicon.png" width="100%"/>
                        </span>
                        <span class="app-brand-text demo menu-text fw-bold ms-2">دارایی</span>
                    </a>

                    <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto">
                        <i class="bx menu-toggle-icon d-none d-xl-block fs-4 align-middle"></i>
                        <i class="bx bx-x d-block d-xl-none bx-sm align-middle"></i>
                    </a>
                </div>

                <div class="menu-divider mt-0"></div>

                <div class="menu-inner-shadow"></div>

                <ul class="menu-inner py-1">
                    <!-- Page -->
                    <li class="menu-item active">
                        <a asp-controller="Home" asp-action="Index" class="menu-link">
                            <i class="menu-icon tf-icons bx bx-chart"></i>
                            <div>داشبورد</div>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a asp-controller="Place" asp-action="Index" class="menu-link">
                            <i class="menu-icon tf-icons bx bx-home-circle"></i>
                            <div>اتاق ها</div>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a href="javascript:void(0);" class="menu-link menu-toggle">
                            <i class="menu-icon tf-icons bx bx-box"></i>
                            <div>اموال</div>
                        </a>
                        <ul class="menu-sub">
                            <li class="menu-item">
                                <a asp-controller="Property" asp-action="Index" class="menu-link">
                                    <div>لیست</div>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a asp-controller="Property" asp-action="Create" class="menu-link">
                                    <div>افزودن</div>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="menu-item">
                        <a asp-controller="User" asp-action="Index" class="menu-link">
                            <i class="menu-icon tf-icons bx bx-user-circle"></i>
                            <div>کاربران</div>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a asp-controller="Home" asp-action="SignOut" class="menu-link">
                            <i class="menu-icon tf-icons bx bx-exit"></i>
                            <div>خروج از حساب</div>
                        </a>
                    </li>
                </ul>
            </aside>
            <!-- / Menu -->
            <!-- Layout container -->
            <div class="layout-page">
                <!-- Navbar -->

                <nav class="layout-navbar navbar navbar-expand-xl align-items-center bg-navbar-theme" id="layout-navbar">
                    <div class="container-fluid">

                        <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
                            <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                                <i class="bx bx-menu bx-sm"></i>
                            </a>
                        </div>

                        <div class="navbar-nav align-items-center">
                            <a class="nav-link style-switcher-toggle hide-arrow" href="javascript:void(0);">
                                <i class="bx bx-sm"></i>
                            </a>
                        </div>

                        <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
                            <ul class="navbar-nav flex-row align-items-center ms-auto">
                                <!-- User -->
                                <li class="nav-item navbar-dropdown dropdown-user dropdown">
                                    <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                                        <div class="avatar avatar-online">
                                            <img src="~/img/admin/Default.png" class="rounded-circle">
                                        </div>
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-end">
                                        <li>
                                            <a class="dropdown-item" href="#">
                                                <div class="d-flex">
                                                    <div class="flex-shrink-0 me-3">
                                                        <div class="avatar avatar-online">
                                                            <img src="~/img/admin/Default.png" class="rounded-circle">
                                                        </div>
                                                    </div>
                                                    <div class="flex-grow-1">
                                                        <span class="fw-semibold d-block">جان اسنو</span>
                                                        <small>مدیر</small>
                                                    </div>
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <div class="dropdown-divider"></div>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" asp-controller="User">
                                                <i class="bx bx-user me-2"></i>
                                                <span class="align-middle">پروفایل من</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" asp-controller="User" asp-action="EditMe">
                                                <i class="bx bx-cog me-2"></i>
                                                <span class="align-middle">تنظیمات</span>
                                            </a>
                                        </li>
                                        <li>
                                            <div class="dropdown-divider"></div>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" asp-controller="Home" asp-action="SignOut">
                                                <i class="bx bx-power-off me-2"></i>
                                                <span class="align-middle">خروج</span>
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                                <!--/ User -->
                            </ul>
                        </div>
                    </div>
                </nav>

                <!-- / Navbar -->
                <!-- Content wrapper -->
                <div class="content-wrapper">
                    <!-- Content -->
                    @RenderBody()
                    <!-- / Content -->
                    <!-- Footer -->
                    <footer class="content-footer footer bg-footer-theme">
                        <div class="container-fluid d-flex flex-wrap justify-content-between py-3 flex-md-row flex-column">
                            <div class="mb-2 mb-md-0">
                                طراحی شده با ❤️ در ‌شرکت
                                <a href="https://lightcompany.ir" target="_blank" class="footer-link fw-semibold">لایت کمپانی‌</a>
                            </div>
                            <div>
                                <a href="#" target="_blank" class="footer-link me-4">آموزش</a>
                            </div>
                        </div>
                    </footer>
                    <!-- / Footer -->

                    <div class="content-backdrop fade"></div>
                </div>
                <!-- Content wrapper -->
            </div>
            <!-- / Layout page -->
        </div>

        <!-- Overlay -->
        <div class="layout-overlay layout-menu-toggle"></div>

        <!-- Drag Target Area To SlideIn Menu On Small Screens -->
        <div class="drag-target"></div>
    </div>
    <!-- / Layout wrapper -->
    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="~/lib/jquery/dist/jquery.slim.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/lib/hammer/hammer.js"></script>
    <script src="~/lib/i18n/i18n.js"></script>
    <script src="~/lib/typeahead-js/typeahead.js"></script>
    <script src="~/js/menu.js"></script>
    <!-- endbuild -->
    <!-- Vendors JS -->
    <script src="~/lib/formvalidation/dist/js/formvalidation.min.js"></script>
    <script src="~/lib/formvalidation/dist/js/FormValidation.min.js"></script>
    <script src="~/lib/formvalidation/dist/js/plugins/Bootstrap5.min.js"></script>
    <script src="~/lib/formvalidation/dist/js/plugins/AutoFocus.min.js"></script>

    <!-- Main JS -->
    <script src="~/js/main.js"></script>

    <!-- Page JS -->
    <script src="~/js/pages-auth.js"></script>
    @RenderSection("Scripts", required: false)
    <!-- Page JS -->
</body>
</html>